# configs/config.yaml
server:
  port: "8080"
  timeout: 30

llm:
  type: "perplexity"  # or "openai"
  baseUrl: "https://api.perplexity.ai"  # or "https://api.openai.com/v1"
  model: "llama-3.1-sonar-small-128k-online"  # or "gpt-4" for OpenAI
  maxTokens: 1000
  temperature: 0.7

redis:
  address: "localhost:6379"
  password: ""
  db: 0
